name: Unit tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
          os: [ubuntu-latest]
          python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
          include:
            - os: macos-latest
              python-version: "3.13"
            - os: windows-latest
              python-version: "3.13"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install --upgrade pip
      - name: Install build dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y libpulse-dev libasound2-dev portaudio19-dev
      - name: Install ffmpeg (for Whisper)
        if: runner.os != 'macOS'
        uses: FedericoCarboni/setup-ffmpeg@v3
      - name: Install Python dependencies on Linux
        if: runner.os == 'Linux'
        run: |
          python -m pip install .[dev,audio,pocketsphinx]  # ,whisper-local,whisper-api]
      - name: Install Python dependencies on macOS
        if: runner.os == 'macOS'
        run: |
          brew install portaudio
          python -m pip install --editable .[dev,audio,pocketsphinx,whisper-local,whisper-api]
      - name: Install Python dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          python -m pip install .[dev,whisper-local,whisper-api]
      - name: Test with unittest
        run: |
          pytest --doctest-modules -v speech_recognition/recognizers/ tests/
